version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          key: MyJourney2Pro-{{ checksum "pom.xml" }}
      - run:
          name: Run Maven verify
          command: mvn clean verify -PmavenCentral
      - save_cache:
          paths:
            - ~/.m2
          key: MyJourney2Pro-{{ checksum "pom.xml" }}

workflows:
  build-and-test:
    jobs:
      - test
